version: '3.3'
services:
  prometheus:
    user: root
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: localhost
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/config:/config'
      - './prometheus/config/alert_rules.yml:/etc/prometheus/alert_rules.yml'
      - './prometheus/data/prometheus:/prometheus/data'
    command:
      - '--config.file=/config/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - prometheus
  blackbox_exporter:
    image: prom/blackbox-exporter
    restart: always
    tty: true
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-backbox.rule=Host(`blackbox_exporter`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-backbox.loadbalancer.server.port=9115
    ports:
      - 9115:9115
    dns: 8.8.8.8
    command: --config.file=/etc/blackbox/blackbox.yml
    volumes:
      - ./blackbox/:/etc/blackbox/
    networks:
      - prometheus
  alertmanager:
    image: prom/alertmanager:v0.19.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - '9093:9093'
    networks:
      - prometheus
  grafana:
    user: root
    image: grafana/grafana:latest
    container_name: grafana
    hostname: localhost
    restart: always
    ports:
      - '3000:3000'
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=60A@truongson"
    volumes:
      - './grafana/config/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml'
      - './grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - './grafana/data/grafana:/var/lib/grafana'
    networks:
      - prometheus
networks:
  prometheus:
    driver: bridge
