version: '3.3'
services:
  prometheus:
   # Run Container as root user
    user: root
    image: prom/prometheus:v2.33.5
    container_name: prometheus
    hostname: localhost
    restart: always
    ports:
      - '9090:9090'
   # Mount config file from local to Container
    volumes:
      - './prometheus/config:/config'
      - './prometheus/config/alert_rules.yml:/etc/prometheus/alert_rules.yml'
      - './prometheus/data/prometheus:/prometheus/data'
   # Container start CMD to load config file   
    command:
      - '--config.file=/config/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - prometheus
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: localhost
    restart: unless-stopped
    volumes:
      - ./proc:/host/proc:ro
      - ./sys:/host/sys:ro
      - ./:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9100:9100'
    networks:
      - prometheus
  alertmanager:
    # Run Container as root user
    user: root
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    hostname: localhost
    restart: always
    ports:
      - '9093:9093'
   # Mount config file from local to Container  
    volumes:
      - './prometheus/config:/config'
      - './prometheus/data/alertmanager:/alertmanager/data'
   # Container start CMD to load config file   
    command:
      - '--config.file=/config/alertmanager.yml'
    networks:
      - prometheus
  grafana:
     # Run Container as root user
    user: root
    image: grafana/grafana:8.4.3
    container_name: grafana
    hostname: localhost
    restart: always
    ports:
      - '3000:3000'
   # Mount config file from local to Container     
    volumes:
      - './grafana/config/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml'       
      - './grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - './grafana/data/grafana:/var/lib/grafana'
    networks:
      - prometheus
  
networks:
  prometheus:
    driver: bridge
     

