version: '3.3'
services:
  prometheus:
    user: root
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: localhost
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/config:/config'
      - './prometheus/config/alert_rules.yml:/etc/prometheus/alert_rules.yml'
      - './prometheus/data/prometheus:/prometheus/data'
    command:
      - '--config.file=/config/prometheus.yml'
      - '--web.enable-lifecycle'
    networks:
      - prometheus
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: localhost
    restart: unless-stopped
    volumes:
      - ./proc:/host/proc:ro
      - ./sys:/host/sys:ro
      - ./:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - '9100:9100'
    networks:
      - prometheus
  alertmanager:
    image: prom/alertmanager:v0.19.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - '9093:9093'
    networks:
      - prometheus
  grafana:
    user: root
    image: grafana/grafana:latest
    container_name: grafana
    hostname: localhost
    restart: always
    ports:
      - '3000:3000'
    environment:
      - "GF_SECURITY_ADMIN_USER=admin"
      - "GF_SECURITY_ADMIN_PASSWORD=60A@truongson"
    volumes:
      - './grafana/config/grafana_datasources.yml:/etc/grafana/provisioning/datasources/all.yaml'
      - './grafana/config/grafana.ini:/etc/grafana/grafana.ini'
      - './grafana/data/grafana:/var/lib/grafana'
    networks:
      - prometheus
  loki:
    image: grafana/loki:2.8.3
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - prometheus

  promtail:
    image: grafana/promtail:2.8.3
    volumes:
      - /ovar/log:/var/log
      - ./loki/promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - prometheus
networks:
  prometheus:
    driver: bridge
