global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:9090"]
  - job_name: "node"
    static_configs:
    - targets: ["192.168.1.184:9100"]
  - job_name: "wordpress"
    static_configs:
    - targets: ["192.168.1.200:9100"]
  - job_name: "mysql"
    static_configs:
    - targets: ["192.168.1.200:9104"]
rule_files:
  - ./alert_rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
remote_write:
  - url: "localhost:3000"
    basic_auth:
      username: "admin"
      password: "VienDong@123"
