global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'GOFNB'
    scrape_interval: 5s
    file_sd_configs:
      - files:
        - ./windows-exporter-gofnb.json
  - job_name: 'SOURCE-VN'
    scrape_interval: 5s
    file_sd_configs:
      - files:
        - ./windows-exporter-source-vn.json
rule_files:
  - ./alert_rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
remote_write:
  - url: "localhost:3000"
    basic_auth:
      username: "admin"
      password: "60A@truongson"